Repository softeerbootcamp/Team7-Amatta, pull requests merged in 2023-02, with the labels that each got.

#9 (#8) - 프로젝트 구조 세팅
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepositoryImpl.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserJoinDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserLoginDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/model/Users.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepositoryImpl.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/UserService.java
Labels: ✨ Feature

#22 BE - 회원가입 기능 구현
  amatta_server/build.gradle
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserJoinDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserJoinReq.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserJoinRes.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepositoryImpl.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/UserService.java
Labels: ✨ Feature

#27 FE- 회원가입 페이지 UI 개발
  client/src/assets/logo-pink.png
  client/src/styles/auth.scss
  client/src/styles/color.scss
  client/src/styles/common.scss
  client/src/styles/header.scss
  client/src/styles/main.scss
  client/src/views/signupView.ts
Labels: ✨ Feature

#29 FE - SPA Router 구현
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/apis/client.ts
  client/src/assets/logo-mint .png
  client/src/assets/logo-pink.png
  client/src/assets/logo-white.png
  client/src/assets/main-logo.png
  client/src/assets/search.svg
  client/src/components/common/InputForm.ts
  client/src/components/common/header.ts
  client/src/components/common/index.ts
  client/src/constants/constant.ts
  client/src/main.ts
  client/src/pages/AuthPage.ts
  client/src/pages/HomePage.ts
  client/src/pages/MainPage.ts
  client/src/pages/NotFoundPage.ts
  client/src/pages/index.ts
  client/src/styles/auth.scss
  client/src/styles/common.scss
  client/src/styles/home.scss
  client/src/utils/index.ts
  client/src/utils/templateGenerator.ts
  client/src/views/headerView.ts
  client/src/views/signupView.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: ✨ Feature

#30 Be - AOP 쿠키 검증 테스트
  amatta_server/src/main/java/com/amatta/amatta_server/aop/AuthorizationAop.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: ✅ Test

#32 BE - Never Clova OCR API 연동 API 구현
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonImageDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonTextDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/NaverAPIRequestGenerator.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/RequestGenerator.java
Labels: ✨ Feature

#43 BE - redirect 요청 api 생성
  amatta_server/src/main/java/com/amatta/amatta_server/index/IndexController.java
Labels: ✨ Feature

#48 BE - 유저 관련 기능 테스트 코드 작성
  amatta_server/src/test/java/com/amatta/amatta_server/user/UserControllerTest.java
Labels: ✅ Test

#51 Be - 유저 이메일 찾기 기능 추가
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserFindEmailReq.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserFindEmailRes.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserPhoneNumExistRes.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/model/Users.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/UserService.java
Labels: ✨ Feature

#55 BE - 텍스트 정보를 기프티콘으로 매핑하는 기능 추가
  amatta_server/build.gradle
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/enums/GifticonMapperEnum.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/GifticonMapper.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/GifticonMapperFactory.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/KakaoGifticonMapper.java
Labels: ✨ Feature

#59 BE - 텍스트 -> 기프티콘 매핑 시 바코드 번호 포함하는 기능 추가
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/KakaoGifticonMapper.java
Labels: ✨ Feature

#61 BE - 기프티콘 등록 API
  amatta_server/src/main/java/com/amatta/amatta_server/exception/DuplicateGifticonException.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepositoryImpl.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: ✨ Feature

#65 BE - CrossOrigin 수정
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#66 Fe - 메인 페이지 구현 코드 refactor
  README.md
  client/src/components/common/CardDetail.js
  client/src/components/common/header.js
  client/src/components/common/index.js
  client/src/main.js
  client/src/pages/AuthPage.js
  client/src/pages/MainPage.js
  client/src/pages/MainPage.ts
  client/src/pages/SlidePage.js
  client/src/pages/index.js
  client/src/styles/main.scss
  client/src/styles/style.scss
  client/src/utils/index.js
  client/src/utils/slider.js
Labels: 🔨 Refactor

#68 BE - AOP에서 쿠키를 이용한 세션 검증
  amatta_server/src/main/java/com/amatta/amatta_server/aop/AuthorizationAop.java
Labels: ✨ Feature

#71 FE - CI 초기설정(#70)
  client/package.json
  client/src/apis/client.js
Labels: ⚙ Setting

#74 FE - 함수 수정
  client/src/components/common/header.js
  client/src/main.js
  client/src/pages/MainPage.js
  client/src/pages/SlidePage.js
  client/src/pages/index.js
  client/src/styles/main.scss
  client/src/utils/slider.js
Labels: 🔨 Refactor

#76 BE - 이메일로 비밀번호 찾기 기능 구현
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserFindPasswordByEmailReq.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserFindPasswordByEmailRes.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/MailService.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/UserService.java
Labels: ✨ Feature

#80 Fe - feature/posting
  client/src/components/common/header.js
  client/src/components/common/index.js
  client/src/main.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/pages/index.js
  client/src/styles/post.scss
  client/src/styles/style.scss
  client/src/utils/domFx.js
  client/src/utils/drag.js
  client/src/utils/index.js
Labels: ✨ Feature

#81 BE - 기프티콘 리스트 조회 API
  amatta_server/src/main/java/com/amatta/amatta_server/exception/GifticonNotSupportedException.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/GifticonMapper.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/GifticonMapperFactory.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/KakaoGifticonMapper.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/NoMatchMapper.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: ✨ Feature

#84 BE - 기프티콘 사용 처리 API 구현
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: ✨ Feature

#90 BE : cors 해결을 위한 CrossOrigin 수정
  amatta_server/src/main/java/com/amatta/amatta_server/index/IndexController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#91 BE - cors 해결을 위찬 추가 수정
  amatta_server/src/main/java/com/amatta/amatta_server/index/IndexController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#94 BE - 로그인 시 브라우저에 쿠키 남지 않던 오류 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#96 BE - 로그인 시 브라우저에 쿠키 남지 않던 오류 추가 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#97 BE - 로그인 시 브라우저에 쿠키 남지 않던 오류 추가 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#101 BE - 기프티콘 객체에 thumbnail 멤버 변수 추가
  amatta_server/build.gradle
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: ✨ Feature

#105 BE - 마이페이지 기능 구현
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/dto/UserMypageRes.java
Labels: ✨ Feature

#109 FE - feature/card slider
  client/src/pages/MainPage.js
  client/src/styles/main.scss
  client/src/utils/slider.js
  client/src/utils/sliderEx.js
Labels: 🔨 Refactor

#112 BE - Firebase Cloud Messaging 관련 setup 및 기본 구현
  amatta_server/.gitignore
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/FCMInitializer.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/dto/TokenRegisterDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/model/FCMToken.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/repository/DeviceTokenRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/repository/UserRepository.java
  amatta_server/src/test/java/com/amatta/amatta_server/FCMRepoTest.java
Labels: ✨ Feature

#114 BE - exception message 하드코딩 제거
  amatta_server/src/main/java/com/amatta/amatta_server/exception/DuplicateGifticonException.java
  amatta_server/src/main/java/com/amatta/amatta_server/exception/GifticonNotSupportedException.java
  amatta_server/src/main/java/com/amatta/amatta_server/exception/NotAuthenticatedException.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDto.java
Labels: 🔨 Refactor

#115 BE - UserControllerTest mockMvc 사용으로 수정
  amatta_server/src/test/java/com/amatta/amatta_server/user/UserControllerTest.java
Labels: ✅ Test

#117 BE : 쿠키 관련 설정 properties에 저장 및 코드 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#118 BE - 임시 비밀번호 메일 제목 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/MailService.java
Labels: ✨ Feature

#119 BE - crossOrigin localhost 삭제
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: 🐞 BugFix

#121 BE - firebase key 정보를 properties에 저장된 문자열로 읽어오도록 변경
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/FCMInitializer.java
Labels: 🔨 Refactor

#123 BE - 다른 테스트를 위해 FCM 관련 설정 주석처리(#122)
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/FCMInitializer.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: 🐞 BugFix, ✅ Test

#125 BE - FCMInitializer 수정
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/FCMInitializer.java
Labels: ✨ Feature

#126 BE - local환경에서 테스트 할 수 있도록 origins 추가
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#129 BE - FCM 푸시 알림 테스트를 위한 주석 해제(#128)
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✨ Feature

#132 Be refactor/fcm
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/FCMInitializer.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: 🔨 Refactor, ✅ Test

#134 test(BE) : Fcm message test (#128)
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
Labels: ✅ Test

#137 [테스트] : FCM 웹 푸시 테스트 및 토큰 출력
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✅ Test

#138 BE - 여러 기기로 알림 보내는 기능 테스트
  amatta_server/build.gradle
  amatta_server/src/main/java/com/amatta/amatta_server/AmattaServerApplication.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/repository/DeviceTokenRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✅ Test

#139 BE : lombok 의존성 수정
  amatta_server/build.gradle
Labels: 🐞 BugFix, ✅ Test

#143 BE - 만료가 임박한 기프티콘에 대한 알림 전송 기능 구현
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/repository/DeviceTokenRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/test/java/com/amatta/amatta_server/DatabaseTest.java
Labels: ✨ Feature

#144 BE - cors 해결을 위한 crossorigin 수정
  amatta_server/src/main/java/com/amatta/amatta_server/index/IndexController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: 🐞 BugFix

#146 BE - cors 오류 해결을 위한 cross origin 수정
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/index/IndexController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: 🐞 BugFix

#148 BE - 세션이 만료된 상태의 요청에 대해 internal server error 가 뜨던 현상 수정
  amatta_server/src/main/java/com/amatta/amatta_server/aop/AuthorizationAop.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: 🐞 BugFix

#150 BE - 머지 실수로 프론트 코드도 수정된것 롤백
  client/src/main.js
Labels: 🐞 BugFix

#154 BE - 로컬에서 테스트시 preflight 오류 해결을 위한 어노테이션 추가
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: 🐞 BugFix

#157 BE - 기프티콘 사용 처리 쿼리문 수정
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonUseDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/test/java/com/amatta/amatta_server/GifticonControllerTest.java
Labels: 🐞 BugFix

#158 BE : 로컬에서 테스트 하기 위한 기프티콘 관련 기능 수정
  amatta_server/src/main/java/com/amatta/amatta_server/aop/AuthorizationAop.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: ✅ Test

#160 BE - 기프티콘 사진 저장 방식 변경
  amatta_server/build.gradle
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/AWSConfig.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: ✨ Feature

#162 FE - FCM 토큰 발급 및 포그라운드, 백그라운드 메세지 이벤트 추가
  client/firebase-messaging-sw.js
  client/src/components/auth/login.js
  client/src/main.js
Labels: ✨ Feature

#165 BE - DB image, thumbnail 타입 변경으로 인한 오류 해결
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/model/Gifticon.java
Labels: 🐞 BugFix

#166 BE - 토큰 받아오지 못하던 오류 해결 및 아이콘 테스트를 위한 코드 추가
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/dto/TokenRegisterDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✨ Feature

#174 BE - 알림 클릭시 기프티콘 리스트 보여주는 페이지로 이동하도록 수정
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✨ Feature

#178 BE - 로그아웃 시 FCM 토큰 제거 추가 및 기프티콘 매핑 수정
  amatta_server/src/main/java/com/amatta/amatta_server/exception/GifticonParseException.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/controller/FCMController.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/dto/TokenRegisterDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/repository/DeviceTokenRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/enums/GifticonMapperEnum.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/KakaoGifticonMapper.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/util/NoMatchMapper.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/service/UserService.java
  amatta_server/src/test/java/com/amatta/amatta_server/DatabaseTest.java
  amatta_server/src/test/java/com/amatta/amatta_server/user/UserControllerTest.java
Labels: 🐞 BugFix, ✨ Feature

#180 BE - 기프티콘 검색 기능, 사용 완료 기프티콘 출력 기능, 메인에서 사용 완료한 기프티콘 출력하지 않는 기능 추가
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: ✨ Feature

#181 BE - 로컬에서 테스트를 위한 mypage 메소드 수정
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#185 feat(FE) : 검색 기능 추가(#164)
  client/assets/icon-x128.png
  client/assets/icon-x192.png
  client/assets/icon-x384.png
  client/assets/icon-x512.png
  client/manifest.json
  client/service-worker.js
  client/src/apis/card.js
  client/src/apis/client.js
  client/src/components/auth/login.js
  client/src/components/common/header.js
  client/src/components/main/cardSearch.js
  client/src/components/main/index.js
  client/src/main.js
  client/src/pages/MainPage.js
  client/src/pages/PostPage.js
  client/src/styles/header.scss
  client/src/styles/main.scss
  client/src/utils/domFx.js
  client/vite.config.js
Labels: ✨ Feature

#187 BE - 로그인 시에만 동작할 수 있도록 수정, 기프티콘 등록시 사진 s3에 등록하는 부분 메소드 분리
  amatta_server/src/main/java/com/amatta/amatta_server/aop/AuthorizationAop.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
  amatta_server/src/main/java/com/amatta/amatta_server/user/controller/UserController.java
Labels: ✨ Feature

#189 BE - 테스트를 위해 한시간마다 알림 가도록 설정(#188)
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✅ Test

#191 BE - 기프티콘 삭제 기능 추가
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/controller/GifticonController.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/dto/GifticonDeleteDto.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/repository/GifticonRepository.java
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: ✨ Feature

#194 BE - 푸시 알람 테스트를 위한 스케줄러 수정
  amatta_server/src/main/java/com/amatta/amatta_server/fcm/service/FCMService.java
Labels: ✅ Test

#196 BE - 기프티콘 삭제 하드코딩되어있던 부분 수정
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: 🐞 BugFix

#197 BE - 기프티콘 서비스 AOP 관련 어노테이션 주석 해제
  amatta_server/src/main/java/com/amatta/amatta_server/gifticon/service/GifticonService.java
Labels: 🐞 BugFix
